### ISSUE TITLE
The partner instant exchange SimpleSwap.io

### ISSUE THREAD

**Issue by charlie-selle** [kinecosystem/kin-migration-module-android#2]
Hi,

I am Nicolas, the manager at SimpleSwap.io, an instant cryptocurrency exchange.

We present a simple and easy-to-use platform that works without registration and limits and allows users to make swaps in just two clicks. We have more than 200 currencies available at this moment for smooth exchanges.

I'm sorry that I invaded here, but maybe you can tell me where I can turn. I tried to find contact with your team but without results. I would like to make contact so we can have an interaction.

**Comment by mrsegev** [comment]
Hi Nicolas,
I will pass your message to the relevant people.
However, this is not the place for such interactions. Please avoid creating such issues in the future. 

Best,
